name: "debezium-embedded-postgres"
database.hostname: "testing-db.croyugidmvfp.eu-central-1.rds.amazonaws.com"
database.port: "5432"
database.user: "postgres"
database.password: "cUfH2xfkfYycJlmJLSG1"
database.server.name: "postgres"
schema.include.list: vytalprod
plugin.name: "pgoutput"
table.include.list: "vytalprod.MerchantStores,vytalprod.ContainerLocations,vytalprod.ContainerLocations"
clickhouse.server.url: "https://r7y1lbbp38.eu-west-1.aws.clickhouse.cloud"
clickhouse.server.user: "default"
clickhouse.server.password: "rxJq6XPa4oZ~R"
clickhouse.server.pass: "rxJq6XPa4oZ~R"
clickhouse.server.port: "8443"
clickhouse.server.database: "altinity"
database.allowPublicKeyRetrieval: "true"
snapshot.mode: "initial"
offset.flush.interval.ms: 5000
connector.class: "io.debezium.connector.postgresql.PostgresConnector"
offset.storage: "io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore"
offset.storage.jdbc.offset.table.name: "altinity_sink_connector.replica_source_info"
offset.storage.jdbc.url: "jdbc:clickhouse://r7y1lbbp38.eu-west-1.aws.clickhouse.cloud:8443/altinity_sink_connector?ssl=true"
offset.storage.jdbc.user: "default"
offset.storage.jdbc.password: "rxJq6XPa4oZ~R"
offset.storage.jdbc.pass: "rxJq6XPa4oZ~R"
offset.storage.jdbc.offset.table.ddl: "CREATE TABLE if not exists %s
(
    `id` String,
    `offset_key` String,
    `offset_val` String,
    `record_insert_ts` DateTime,
    `record_insert_seq` UInt64,
    `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY id
SETTINGS index_granularity = 8198"
offset.storage.jdbc.offset.table.delete: "delete from %s where 1=1"
schema.history.internal: "io.debezium.storage.jdbc.history.JdbcSchemaHistory"
schema.history.internal.jdbc.url: "jdbc:clickhouse://r7y1lbbp38.eu-west-1.aws.clickhouse.cloud:8443/altinity_sink_connector?ssl=true"
schema.history.internal.jdbc.user: "default"
schema.history.internal.jdbc.password: "rxJq6XPa4oZ~R"
schema.history.internal.jdbc.pass: "rxJq6XPa4oZ~R"
schema.history.internal.jdbc.schema.history.table.ddl: "CREATE TABLE if not exists %s
(`id` VARCHAR(36) NOT NULL, `history_data` VARCHAR(65000), `history_data_seq` INTEGER, `record_insert_ts` TIMESTAMP NOT NULL, `record_insert_seq` INTEGER NOT NULL) ENGINE=ReplacingMergeTree(record_insert_seq) order by id"

schema.history.internal.jdbc.schema.history.table.name: "altinity_sink_connector.replicate_schema_history"
enable.snapshot.ddl: "true"
auto.create.tables: "true"
database.dbname: "postgres"
