services:
  postgres:
    image: debezium/postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=public
    volumes:
      - ../sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  ### MONITORING ####
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:2.36.0
    restart: "no"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

  grafana:
    build:
      context: ./config/grafana
      args:
        GRAFANA_VERSION: latest
    #container_name: grafana
    #image: grafana/grafana
    restart: "no"
      #volumes:
    #  - ../config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    environment:
      - DS_PROMETHEUS=prometheus
      - GF_USERS_DEFAULT_THEME=light
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource,grafana-clickhouse-datasource
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource,grafana-clickhouse-datasource
    depends_on:
      - prometheus
    ## END OF MONITORING ###