version: "3.4"

# Ubuntu , set this for redpanda to start
# https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_ubuntu/ch04s03.htm

# Clickhouse Table Schema
# create table test(id int, message String) ENGINE=MergeTree() PRIMARY KEY id;

services:
  postgres:
    image: debezium/postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=public
    volumes:
      - ../sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"


  clickhouse:
    # clickhouse-client --host=127.0.0.1 --port=9000 --user=root --password=root --database=test
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: "no"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=0
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    volumes:
      #- ../sql/init_ch.sql:/docker-entrypoint-initdb.d/init_clickhouse.sql
      -  ../clickhouse/users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    image: zookeeper:3.6.2
    expose:
      - "2181"
    environment:
      ZOO_TICK_TIME: 500
      ZOO_MY_ID: 1
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s
    security_opt:
      - label:disable

  debezium-embedded:
    image: registry.gitlab.com/altinity-public/container-images/clickhouse_debezium_embedded:${SINK_LIGHTWEIGHT_VERSION}
    #    build:
    #      context: ../
    restart: "no"
    ports:
      - "8083:8083"
      - "5005:5005"
    depends_on:
      - clickhouse 
    env_file:
      - docker_postgres.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      #- ./data:/data
      - ./config_postgres.yml:/config.yml
