name: "engine"
offset.storage: "org.apache.kafka.connect.storage.FileOffsetBackingStore"
offset.storage.file.filename: "/tmp/offsets.dat"
offset.flush.interval.ms: "60000"

database.server.name: "clickhouse-ddl"
database.server.id: "976"
database.history: "io.debezium.relational.history.FileDatabaseHistory"
database.history.file.filename: "/tmp/dbhistory.dat"
connector.class: "io.debezium.connector.mysql.MySqlConnector"

converter.schemas.enable: "true"
schemas.enable: "true"
snapshot.mode: "initial"
topic.prefix: "my-app-connector"
schema.history.internal: "io.debezium.storage.file.history.FileSchemaHistory"
