name: testflows tests

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main , develop]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Install testflows
        working-directory: tests/integration
        run: pip3 install testflows

      - name: docker-compose version
        working-directory: tests/integration
        run: docker-compose version

      - name: Run testflows tests
        working-directory: tests/integration
#        run: python3 -u regression.py --only "/mysql to clickhouse replication/*" --clickhouse-binary-path=docker://clickhouse/clickhouse-server:22.8 --test-to-end
        run: python3 -u regression.py --only "/mysql to clickhouse replication/virtual columns/*" --clickhouse-binary-path=docker://clickhouse/clickhouse-server:22.8 --log test.txt
#      - name: Download a single artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: my-artifact
#          path: tests/integration/logs
##      - name: Upload artifacts as release assets
##        if: ${{ github.event_name == 'release' && matrix.build_type == 'Release' }}
##        uses: svenstaro/upload-release-action@v2
##        with:
##          repo_token: ${{ secrets.GITHUB_TOKEN }}
##          file: ${{ github.workspace }}/build/clickhouse-odbc-*
##          overwrite: true
##          tag: ${{ github.ref }}
##          file_glob: true
#
