name: testflows tests

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main , develop]

jobs:
  integration_tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Install testflows
        working-directory: tests/integration
        run: pip3 install testflows

      - name: Download aws
        working-directory: tests/integration
        run: pip3 install awscli

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M%S')"

      - name: Run testflows tests
        working-directory: tests/integration
        run: python3 -u regression.py --only "/mysql to clickhouse replication/*" --clickhouse-binary-path=docker://clickhouse/clickhouse-server:22.8 --test-to-end -o classic --collect-service-logs --log logs/raw.log

      - name: Upload aws S3
        working-directory: tests/integration/logs
        run: aws s3 cp . s3://altinity-test-reports/altinity-sink-connector/testflows-artifacts-${{ steps.date.outputs.date }}/ --recursive --exclude "*" --include "*.log"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testflows-artifacts-${{ steps.date.outputs.date }}
          path: |
            tests/integration/logs/*.log
          if-no-files-found: error
          retention-days: 60



