name: Docker compose tests

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main , develop]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Run testflows tests
        working-directory: tests/testflows
        run: python3 -u regression.py --only "/mysql to clickhouse replication/data consistency/combinatoric restart test/*" -o classic --clickhouse-binary-path=docker://clickhouse/clickhouse-server:22.8.6.71-alpine --test-to-end
#        run: python3 -u mysql_to_clickhouse_replication/regression.py --only "/mysql to clickhouse replication/sanity/*" --clickhouse-binary-path=docker://clickhouse/clickhouse-server:22.8.6.71-alpine --test-to-end
#      - name: Cleaning
#        working-directory: tests/testflows/mysql_to_clickhouse_replication
#        run: sudo rm -rf _instances