name: testflows tests

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main , develop]

jobs:
  integration_tests:
#    runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install testflows
        working-directory: tests/integration
        run: pip3 install testflows

      - name: Install awscli
        working-directory: tests/integration
        run: pip3 install awscli

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M%S')"

      - name: Run testflows tests
        working-directory: tests/integration
        run: python3 -u regression.py --only "/mysql to clickhouse replication/sanity/*" --clickhouse-binary-path=docker://clickhouse/clickhouse-server:22.8 --test-to-end -o classic --collect-service-logs --attr project="$GITHUB_ACTION_PATH" project.id="$GITHUB_RUN_NUMBER" user.name="$GITHUB_ACTOR" github_actions_run="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"--log logs/raw.log

      - name: add tfs path
        working-directory: tests/integration/logs
        run: export PATH=~/.local/bin/tfs:$PATH

      - name: tfs report
        working-directory: tests/integration/logs
        run: cat raw.log | tfs report results | tfs document convert > report.html

      - name: tfs coverage
        working-directory: tests/integration/logs
        run: cat raw.log | tfs report coverage ../requirements/requirements.py | tfs document convert > coverage.html

      - name: Upload artifacts to Altinity Test Reports AWS s3
        working-directory: tests/integration/logs
        run: aws s3 cp . s3://altinity-test-reports/altinity-sink-connector/testflows/${{ steps.date.outputs.date }}_${{github.run.number}}/ --recursive --exclude "*" --include "*.log" --include "*.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testflows-artifacts-${{ steps.date.outputs.date }}
          path: |
            tests/integration/logs/*.log
          if-no-files-found: error
          retention-days: 60



